// Generated by typings
// Source: https://raw.githubusercontent.com/asemblia/CustomTypings/master/pace-progress.d.ts
declare module 'pace' {
    interface PaceOptions {
        catchupTime?: number;
        initialRate?: number;
        ghostTime?: number;
        maxProgressPerFrame?: number;
        easeFactor?: number;
        startOnPageLoad?: boolean;
        restartOnPushState?: boolean;
        restartOnRequestAfter?: boolean;
        target?: string;
        elements?: { checkInterval: number, selectors: string[] },
        eventLag?: { minSamples: number, sampleCount: number; lagThreshold: number; }
        ajax?: { trackMethods: string[], trackWebSockets: boolean, ignoreURLs: string[] },
        extraSources?: PaceSource[];
        document?: boolean;
    }

    interface PaceElement {
        progress: number;
    }

    interface PaceSource {
        progress?: number;
        elements?: PaceElement[]
    }

    interface PaceStatic {
      running: false;
      options: PaceOptions;
      sources: string[];
      trigger(action: string): void;
      start(options : PaceOptions): number;
      go(): number;
      stop(): number;
      restart(): number;
      track(): any;
      ignore(): any;
    }

    var pace : PaceStatic;
    export = pace;
}
